name: Ernte Teilen Site CI
concurrency: ci-${{ github.ref }}
on:
  push:
    branches:
      - '*'
      - '!dependabot/**'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    default:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '16'
      - name: Install dependencies
        working-directory: ./
        run: npm install
      - name: Code linting
        working-directory: ./
        run: npm run lint
      - name: Run Tests
        working-directory: ./
        run: npm test
      #     - name: Run Web Tests
      #       working-directory: ./
      #       run: yarn cypress:run
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: teikei-notifications
          status: SUCCESS
          color: good
          message_id: ${{ steps.slack.outputs.message_id }}
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: teikei-notifications
          status: FAILED
          color: danger
          message_id: ${{ steps.slack.outputs.message_id }}
  deploy-preview:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/preview'
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - name: Notify slack started
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        id: slack
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: teikei-notifications
          status: STARTED
          color: good
      - name: Install dependencies
        working-directory: ./
        run: npm install
      - name: Deploy Preview
        uses: dokku/github-action@v1.0.1
        with:
          # The branch to deploy when pushing to Dokku (default: master)
          branch: master
          ci_branch_name: preview
          ssh_private_key: ${{ secrets.DOKKU_SSH_KEY }}
          git_remote_url: ssh://dokku@${{ secrets.DOKKU_HOST }}:22/teikei-site-preview
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: teikei-notifications
          status: SUCCESS
          color: good
          message_id: ${{ steps.slack.outputs.message_id }}
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: teikei-notifications
          status: FAILED
          color: danger
          message_id: ${{ steps.slack.outputs.message_id }}
  deploy-production:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - name: Notify slack started
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        id: slack
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: teikei-notifications
          status: STARTED
          color: good
      - name: Install dependencies
        working-directory: ./
        run: npm install
      - name: Deploy Production
        uses: dokku/github-action@v1.0.1
        with:
          branch: master
          ci_branch_name: master
          ssh_private_key: ${{ secrets.DOKKU_SSH_KEY }}
          git_remote_url: ssh://dokku@${{ secrets.DOKKU_HOST }}:22/teikei-site
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: teikei-notifications
          status: SUCCESS
          color: good
          message_id: ${{ steps.slack.outputs.message_id }}
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: teikei-notifications
          status: FAILED
          color: danger
          message_id: ${{ steps.slack.outputs.message_id }}
