name: Ernte Teilen Site CI
concurrency: ci-${{ github.ref }}
on:
  push:
    branches:
      - '*'
      - '!dependabot/**'
  workflow_dispatch:
env:
  HUSKY: 0
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build (Astro)
        run: npm run build
  deploy-preview:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/preview'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Deploy Preview
        uses: dokku/github-action@v1.10.0
        with:
          branch: main
          ci_branch_name: preview
          ssh_private_key: ${{ secrets.DOKKU_SSH_KEY }}
          git_remote_url: ssh://dokku@${{ secrets.DOKKU_HOST }}:22/teikei-site-preview
  deploy-production:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Deploy Production
        uses: dokku/github-action@v1.10.0
        with:
          branch: main
          ci_branch_name: main
          ssh_private_key: ${{ secrets.DOKKU_SSH_KEY }}
          git_remote_url: ssh://dokku@${{ secrets.DOKKU_HOST }}:22/teikei-site
